/**
 * Learning memory — the store half (the distiller lives in agent-core).
 *
 * Durable, repo-specific lessons the agent has learned from past runs, kept in
 * `.bandit/lessons.md`. It's plain markdown on purpose: human-readable,
 * git-committable, and auto-injected on future turns because `.bandit/lessons.md`
 * is a memory CANDIDATE (see memory.ts). The header makes clear these are
 * machine-distilled and editable/removable, so they read as a lower-trust tier
 * than hand-written BANDIT.md.
 *
 * Kept deliberately small: distillation is conservative (most turns learn
 * nothing), new lessons are deduped, and the store is capped. A big lessons
 * file is a smell — it means the distiller is too eager.
 */
import * as fs from 'fs';
import * as path from 'path';
import { normalizeLesson } from '@burtson-labs/agent-core';

const LESSONS_REL = path.join('.bandit', 'lessons.md');
const HEADER = [
  '# Learned lessons',
  '',
  '<!-- Auto-generated by Bandit from past runs — durable facts about THIS repo.',
  '     Machine-distilled and lower-trust than BANDIT.md: edit freely, or clear',
  '     with `/lessons clear`. Bandit reads this back on future turns. -->',
  ''
].join('\n');

/** Hard cap — beyond this the store is noise, so the oldest fall off. */
const MAX_LESSONS = 40;
const BULLET = /^- (.+)$/;

export function lessonsPath(cwd: string): string {
  return path.resolve(cwd, LESSONS_REL);
}

/** Read the current lessons (bullet lines), newest last. Missing file = []. */
export function loadLessons(cwd: string): string[] {
  let raw: string;
  try {
    raw = fs.readFileSync(lessonsPath(cwd), 'utf-8');
  } catch {
    return [];
  }
  const out: string[] = [];
  for (const line of raw.split('\n')) {
    const m = BULLET.exec(line.trim());
    if (m) out.push(m[1].trim());
  }
  return out;
}

export interface AddLessonResult {
  added: boolean;
  /** Why it wasn't added, when added=false. */
  reason?: 'duplicate' | 'empty';
  total: number;
}

/**
 * Add a lesson, skipping near-duplicates (normalized-equal to an existing
 * one). Enforces the cap by dropping the oldest. Best-effort persistence —
 * returns added:false rather than throwing on a write failure.
 */
export function addLesson(cwd: string, lesson: string): AddLessonResult {
  const clean = lesson.trim();
  const existing = loadLessons(cwd);
  if (!clean) return { added: false, reason: 'empty', total: existing.length };
  const norm = normalizeLesson(clean);
  if (existing.some((l) => normalizeLesson(l) === norm)) {
    return { added: false, reason: 'duplicate', total: existing.length };
  }
  const next = [...existing, clean].slice(-MAX_LESSONS);
  writeLessons(cwd, next);
  return { added: true, total: next.length };
}

/** Remove all lessons (deletes the file). */
export function clearLessons(cwd: string): void {
  try {
    fs.rmSync(lessonsPath(cwd), { force: true });
  } catch {
    /* already gone */
  }
}

function writeLessons(cwd: string, lessons: string[]): void {
  try {
    const abs = lessonsPath(cwd);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    const body = lessons.map((l) => `- ${l}`).join('\n');
    fs.writeFileSync(abs, `${HEADER}${body}\n`, 'utf-8');
  } catch {
    /* best-effort — a learning-memory write must never break a turn */
  }
}
