/**
 * `/memory migrate` wizard runtime.
 *
 * Two-step flow:
 *
 *   1. PLAN   (`/memory migrate`) — the slash command queues a prompt
 *      that asks the agent to read existing BANDIT.md / CLAUDE.md /
 *      AGENTS.md / MEMORY.md, draft topic splits + a fresh BANDIT.md,
 *      and write everything to `.bandit/migration-preview/` along
 *      with a `plan.json` manifest. Nothing in the workspace root
 *      changes during PLAN.
 *
 *   2. APPLY  (`/memory migrate apply`) — this module's `runWizard()`.
 *      Reads the manifest, walks the user through each proposed file
 *      with [a]ccept / [e]dit / [s]kip / [q]uit, optionally spawns an
 *      editor on the staged file for [e], and on completion copies
 *      the accepted staging files into their target paths (saving the
 *      original BANDIT.md as `BANDIT.md.before-migration` first).
 *
 * Why two slash commands instead of one big one: the plan needs to be
 * generated by the agent (an LLM call), which finishes turns at its own
 * pace. Splitting plan / apply gives the user a natural pause to review
 * `.bandit/migration-preview/` in their editor of choice before they
 * commit to anything, even when the wizard's [e] step is one option.
 */
import * as fs from 'fs';
import * as path from 'path';
import { c } from './ansi';
import {
  resolveEditor,
  spawnEditorOnFile,
  type ResolvedEditor
} from './editorSpawn';

export const STAGING_DIR = '.bandit/migration-preview';
export const PLAN_FILE = 'plan.json';

export interface MigrationPlanEntry {
  /**
   * `topic` — a `memory/<slug>.md` file split out of the source memory.
   * `bandit` — the new BANDIT.md that will replace the old one.
   * `index` — a fresh MEMORY.md with hooks for the topics above.
   */
  kind: 'topic' | 'bandit' | 'index';
  /** Path relative to STAGING_DIR — where the proposal currently lives. */
  stagingPath: string;
  /** Path relative to the workspace root — where the file will land on apply. */
  targetPath: string;
  /** Display title — derived from the topic's H1 or used as the section label. */
  title: string;
  /** Topic hook line (only for `kind: 'topic'`). */
  hook?: string;
  /** Approximate line count, used in the wizard preview header. */
  lines: number;
}

export interface MigrationPlan {
  version: 1;
  generatedAt: string;
  sourceFiles: string[];
  entries: MigrationPlanEntry[];
}

/**
 * Caller-supplied capability bag. The wizard is host-agnostic — it gets
 * a way to read one line of input and a way to drive an editor session
 * (which the host has to pause/resume ink around). cli.ts provides both;
 * other hosts could too if we ever ship a non-CLI wizard.
 */
export interface MigrateWizardDeps {
  cwd: string;
  /** Read one line from the user. Should display whatever prompt the
   *  wizard just printed (the wizard handles its own prompt rendering).
   *  Returns the trimmed line. */
  getLine: () => Promise<string>;
  /** Run an editor on a file. Implementor handles the ink/readline
   *  pause/resume dance and the actual child-process spawn. Resolves
   *  when the editor exits. */
  editFile: (filePath: string) => Promise<{ exitCode: number }>;
  /** Optional — when present, called before each editor spawn so the
   *  caller can render a tasteful "── editing X · save+exit when done ──"
   *  banner. Pure UX; the wizard works without it. */
  onBeforeEdit?: (entry: MigrationPlanEntry, editor: ResolvedEditor) => void;
}

interface WizardOutcome {
  applied: number;
  skipped: number;
  edited: number;
  quit: boolean;
  /** Path to the saved-original BANDIT.md, when a BANDIT.md replacement
   *  was part of the plan AND was accepted. Empty when no replacement
   *  was applied. */
  originalBackup: string;
}

/**
 * Load the plan manifest written by the PLAN step. Returns null when the
 * staging dir doesn't exist or the file is malformed — caller prints a
 * "run /memory migrate first" hint and bails.
 */
export async function loadPlan(cwd: string): Promise<MigrationPlan | null> {
  const planPath = path.join(cwd, STAGING_DIR, PLAN_FILE);
  let raw: string;
  try {
    raw = await fs.promises.readFile(planPath, 'utf-8');
  } catch {
    return null;
  }
  try {
    const parsed = JSON.parse(raw) as MigrationPlan;
    if (
      parsed.version !== 1 ||
      !Array.isArray(parsed.entries) ||
      parsed.entries.length === 0
    ) {
      return null;
    }
    return parsed;
  } catch {
    return null;
  }
}

/**
 * Run the interactive wizard. The caller (cli.ts) wires up `getLine` to
 * its replGetLine + `editFile` to a function that pauses ink, spawns the
 * resolved editor, and resumes ink. The wizard owns stdout printing for
 * the preview headers and the per-file picker prompts; it does NOT touch
 * stdin directly so the caller stays in charge of the input layer.
 */
export async function runWizard(deps: MigrateWizardDeps): Promise<WizardOutcome> {
  const plan = await loadPlan(deps.cwd);
  if (!plan) {
    process.stdout.write(c.red('No migration plan found. ') +
      c.dim(`Run ${c.cyan('/memory migrate')} first to generate one, ` +
        `then ${c.cyan('/memory migrate apply')} to launch this wizard.\n`));
    return { applied: 0, skipped: 0, edited: 0, quit: true, originalBackup: '' };
  }

  const editor = resolveEditor();
  if (!editor) {
    process.stdout.write(c.red('No editor available. ') +
      c.dim('Set $EDITOR (e.g. ') + c.cyan('EDITOR=code') + c.dim(') or ') +
      c.cyan('EDITOR=nano') + c.dim(' and rerun ') +
      c.cyan('/memory migrate apply') + c.dim('. ') +
      c.dim('You can also edit the files under ') + c.cyan(STAGING_DIR) +
      c.dim(' directly with any editor before running apply — the wizard reads them as-is.\n'));
    return { applied: 0, skipped: 0, edited: 0, quit: true, originalBackup: '' };
  }

  // Header — louder than the streamed agent output around it so the
  // user can scan-find where the wizard starts. Boxed title block +
  // the picker-key legend in full color rather than dim, since the
  // earlier dim version got lost in tool-call scrollback.
  const headerBar = '═'.repeat(60);
  process.stdout.write('\n' + c.accent(headerBar) + '\n');
  process.stdout.write(c.bold(c.accent('  MEMORY MIGRATION — review proposals')) + '\n');
  process.stdout.write(c.accent(headerBar) + '\n');
  process.stdout.write(c.dim(`  ${plan.entries.length} proposed files from ${plan.sourceFiles.join(', ')}\n`));
  process.stdout.write(c.dim(`  editor: ${editor.label}\n`));
  process.stdout.write(c.dim('  For each file:  ') +
    c.bold(c.accent('[a]')) + c.dim(' accept   ') +
    c.bold(c.accent('[e]')) + c.dim(' edit   ') +
    c.bold(c.accent('[s]')) + c.dim(' skip   ') +
    c.bold(c.accent('[q]')) + c.dim(' quit\n\n'));

  // Per-file decisions. We collect choices first, apply at the end —
  // means a [q]uit at any step leaves the workspace untouched.
  const decisions: Array<{ entry: MigrationPlanEntry; choice: 'accept' | 'skip' }> = [];
  let editedCount = 0;
  for (let i = 0; i < plan.entries.length; i += 1) {
    const entry = plan.entries[i];
    // Big visible separator + step counter + bold filename — the
    // earlier dim divider got buried under tool-result scrollback.
    // User feedback after first wizard ride: "couldn't see the
    // confirm text for each file." This is the louder version.
    process.stdout.write('\n');
    process.stdout.write(c.accent('━'.repeat(60)) + '\n');
    process.stdout.write(
      c.bold(c.accent(`  FILE ${i + 1} of ${plan.entries.length}  `)) +
      c.dim(`(${entry.kind}, ${entry.lines} lines)`) + '\n'
    );
    process.stdout.write(c.bold('  ' + entry.targetPath) + '\n');
    if (entry.hook) {
      process.stdout.write(c.dim('  hook: ') + entry.hook + '\n');
    }
    if (entry.kind === 'bandit') {
      process.stdout.write(c.yellow(c.bold(`  ⚠ this will REPLACE your existing BANDIT.md`)) + '\n');
      process.stdout.write(c.dim('     (original kept as BANDIT.md.before-migration before the swap)') + '\n');
    }
    process.stdout.write(c.accent('━'.repeat(60)) + '\n');

    // Preview — first ~12 lines from the staging file.
    const stagedAbs = path.join(deps.cwd, STAGING_DIR, entry.stagingPath);
    try {
      const body = await fs.promises.readFile(stagedAbs, 'utf-8');
      const preview = body.split('\n').slice(0, 12).map((ln) => c.dim('  │ ') + ln).join('\n');
      process.stdout.write(preview + '\n');
      const totalLines = body.split('\n').length;
      if (totalLines > 12) {
        process.stdout.write(c.dim(`  │ … (${totalLines - 12} more lines)\n`));
      }
    } catch {
      process.stdout.write(c.red(`  ! could not read ${stagedAbs}\n`));
      decisions.push({ entry, choice: 'skip' });
      continue;
    }

    // Picker loop — re-prompt on unknown input so the user doesn't have
    // to redo the whole wizard if they fat-finger the response. Bold
    // letter keys + clear `>` so the prompt is unmistakeable next to
    // scrollback content above it.
    let decision: 'accept' | 'skip' | 'quit' | null = null;
    while (decision === null) {
      process.stdout.write('\n' + c.bold(c.accent('  Your choice: ')) +
        c.bold(c.accent('[a]')) + c.dim('ccept  ') +
        c.bold(c.accent('[e]')) + c.dim('dit  ') +
        c.bold(c.accent('[s]')) + c.dim('kip  ') +
        c.bold(c.accent('[q]')) + c.dim('uit  ') +
        c.bold(c.accent('>')) + ' ');
      const raw = (await deps.getLine()).trim().toLowerCase();
      if (raw === 'a' || raw === 'accept' || raw === 'y' || raw === 'yes') {
        decision = 'accept';
      } else if (raw === 's' || raw === 'skip' || raw === 'n' || raw === 'no') {
        decision = 'skip';
      } else if (raw === 'q' || raw === 'quit' || raw === 'exit') {
        decision = 'quit';
      } else if (raw === 'e' || raw === 'edit') {
        deps.onBeforeEdit?.(entry, editor);
        const { exitCode } = await deps.editFile(stagedAbs);
        if (exitCode !== 0) {
          process.stdout.write(c.yellow(`  ⚠ editor exited with code ${exitCode} — keeping original staged content\n`));
        } else {
          editedCount += 1;
          process.stdout.write(c.dim(`  ✓ saved — re-prompting for accept/skip\n`));
        }
        // After an edit, fall through and re-prompt — the user might
        // want to edit again, accept, or skip. They're never auto-
        // accepted off an edit, which matches what most "git rebase -i"
        // / "crontab -e" users expect.
      } else {
        process.stdout.write(c.dim(`  unknown — type a, e, s, or q\n`));
      }
    }
    if (decision === 'quit') {
      process.stdout.write(c.yellow('  ↷ quit — no files written\n'));
      return { applied: 0, skipped: 0, edited: editedCount, quit: true, originalBackup: '' };
    }
    decisions.push({ entry, choice: decision });
  }

  // Apply phase — only runs when the user reached the end of the wizard.
  process.stdout.write(c.dim('────────────────────────────────────────────────\n'));
  const accepted = decisions.filter((d) => d.choice === 'accept');
  const skipped = decisions.length - accepted.length;
  if (accepted.length === 0) {
    process.stdout.write(c.yellow(`✓ done — nothing applied (you skipped all ${skipped} files).\n`));
    return { applied: 0, skipped, edited: editedCount, quit: false, originalBackup: '' };
  }

  let originalBackup = '';
  const banditReplace = accepted.find((d) => d.entry.kind === 'bandit');
  if (banditReplace) {
    const targetAbs = path.join(deps.cwd, banditReplace.entry.targetPath);
    try {
      const exists = await fs.promises.stat(targetAbs).then(() => true).catch(() => false);
      if (exists) {
        const backupAbs = `${targetAbs}.before-migration`;
        await fs.promises.copyFile(targetAbs, backupAbs);
        originalBackup = path.relative(deps.cwd, backupAbs);
      }
    } catch (err) {
      process.stdout.write(c.red(`✗ could not back up ${banditReplace.entry.targetPath}: ${err instanceof Error ? err.message : String(err)}\n`));
      return { applied: 0, skipped, edited: editedCount, quit: true, originalBackup: '' };
    }
  }

  for (const d of accepted) {
    const stagedAbs = path.join(deps.cwd, STAGING_DIR, d.entry.stagingPath);
    const targetAbs = path.join(deps.cwd, d.entry.targetPath);
    try {
      await fs.promises.mkdir(path.dirname(targetAbs), { recursive: true });
      await fs.promises.copyFile(stagedAbs, targetAbs);
      process.stdout.write(c.green('  ✓ ') + c.dim(d.entry.targetPath) + '\n');
    } catch (err) {
      process.stdout.write(c.red('  ✗ ') + c.dim(`${d.entry.targetPath}: ${err instanceof Error ? err.message : String(err)}\n`));
    }
  }

  // Apply-complete summary block — bordered + green-bold so the result
  // jumps out of scrollback. The earlier single dim line got buried
  // (user feedback after first run: "couldn't see the commit message").
  process.stdout.write('\n');
  process.stdout.write(c.green('═'.repeat(60)) + '\n');
  process.stdout.write(c.bold(c.green(`  ✓ MIGRATION APPLIED  `)) +
    c.dim(`${accepted.length} written, ${skipped} skipped${editedCount > 0 ? `, ${editedCount} edited` : ''}`) + '\n');
  process.stdout.write(c.green('═'.repeat(60)) + '\n');
  if (originalBackup) {
    process.stdout.write(c.dim(`  Original BANDIT.md saved as `) + c.cyan(originalBackup) + '\n');
  }
  process.stdout.write(c.dim(`  Staging dir kept at `) + c.cyan(STAGING_DIR) + c.dim(' — delete when you\'re confident.\n'));
  process.stdout.write(c.dim(`  Run `) + c.cyan('/memory') + c.dim(` to confirm the new shape.\n\n`));

  return {
    applied: accepted.length,
    skipped,
    edited: editedCount,
    quit: false,
    originalBackup
  };
}
